version: '3.7'

services:

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ':9001'
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${NUXT_S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${NUXT_S3_SECRET_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-init:
    image: minio/mc
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio:9000 ${NUXT_S3_ACCESS_KEY} ${NUXT_S3_SECRET_KEY};
      mc mb minio/${NUXT_S3_BUCKET_NAME};
      exit 0;
      "
    depends_on:
      - minio
      
  mongo:
    image: mongo:4.4
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: slack

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: 'mongodb://root:example@mongo:27017/'